camera:
  rtsp_url: "rtsp://admin:QEBRYO@192.168.1.42:554/h264/ch1/sub/av_stream"
  # rtsp_url: "rtsp://admin:QEBRYO@192.168.1.33:554/Streaming/Channels/102"
  # rtsp_url: "rtsp://admin:QEBRYO@192.168.1.33:554/h264/ch1/main/av_stream"

  # Parámetros de optimización
  transport: "tcp"  # TCP es más estable que UDP
  resolution:
    width: 640
    height: 480
  fps: 10
  buffer_size: 1
  reconnect_delay: 2
  max_reconnect_attempts: 5

detection:
  enabled: true
  min_area: 3000
  cooldown_seconds: 10
  sensitivity: 20
  # Optimización de procesamiento
  process_every_n_frames: 2  # Procesar detección cada 3 frames
  log_cooldown_seconds: 5    # Imprimir logs cada 5 segundos
  # Parámetros del Background Subtractor
  background_history: 120
  detect_shadows: false

hardware:
  led_red_pin: 24
  led_green_pin: 23
  buzzer_pin: 22
  buzzer_duration: 60
  led_blink_interval: 0.3

telegram:
  token: "8492390941:AAH1bGSJIL1nPTRiZjM-HNR-IB_HPJvDGhg"
  chat_id: ["1635363596", "6621116239"]
  enabled: true
  send_voice: true
  send_video: true
  send_text: true
  video_duration: 5

schedule:
  alarm_enabled: false  # Estado manual actual
  auto_schedule: true   # Activar programación automática

  schedules:
    - name: "Lunes a Viernes - Noche"
      days: [0, 1, 2, 3, 4]
      start_time: "22:00"
      end_time: "06:00"
      enabled: true

    - name: "Fin de Semana - Noche"
      days: [5, 6]
      start_time: "23:00"
      end_time: "08:00"
      enabled: true

    - name: "Todos los días - Mediodía"
      days: [0, 1, 2, 3, 4, 5, 6]
      start_time: "12:00"
      end_time: "14:00"
      enabled: false

    - name: "Prueba inmediata"
      days: [ 0, 1, 2, 3, 4, 5, 6 ]
      start_time: "17:26"
      end_time: "17:30"
      enabled: true

database:
  path: "events.db"

# Parámetros de streaming web
streaming:
  jpeg_quality: 60  # 0-100, menor = más rápido pero peor calidad
  target_fps: 10    # FPS objetivo para el stream web
  max_width: 640    # Ancho máximo del stream